Using the cleaned, merged DataFrame, compute the following metrics using `pandas`:
1.  **Revenue by Category:** Calculate the total revenue generated (only for "COMPLETED" transactions) grouped by product category.
2.  **Top Spenders:** Identify the top 3 users (`user_id` and `name`) by absolute total spending.
3.  **Return Rate:** Calculate the return rate (number of "RETURNED" items divided by the total number of items) per country.

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("cleaned_dataset.csv")

In [11]:
df_filtered_category = df[df["status"] == "COMPLETED"]

In [9]:
category_result = df_filtered_category.groupby("category")["total_item_value"].sum().reset_index()
category_result

      category  total_item_value
0      Cameras          13599.60
1      Laptops          18937.43
2     Printers           8159.76
3  Smartphones          87570.31
4      Tablets          64535.71

In [22]:
user_result = df.groupby("user_id")["total_item_value"].sum().reset_index()
user_result = user_result.sort_values(by="total_item_value", ascending=False)
user_result = user_result.merge(df[["user_id", "name"]], on="user_id", how="left")
user_result.head(3)

   user_id  total_item_value         name
0       14          50995.42  Kayla Avila
1       14          50995.42  Kayla Avila
2       14          50995.42  Kayla Avila

In [25]:
total_items_per_country = df.groupby("country")["quantity"].sum().reset_index()
total_items_per_country.rename(columns={"quantity": "total_sold_items"}, inplace=True)
total_items_per_country

                     country  total_sold_items
0                     Brazil                23
1                   Djibouti                32
2                      Gabon                61
3                       Iraq                27
4            Kyrgyz Republic                24
5                    Liberia                17
6              Liechtenstein                15
7                   Maldives                36
8                 Martinique                50
9                 Micronesia                20
10               Puerto Rico                14
11               Saint Lucia                24
12  Turks and Caicos Islands                41
13                 Venezuela                25
14                    Zambia                23

In [31]:
df_filtered_status = df[df["status"] == "RETURNED"]
total_returned_items_per_country = df_filtered_status.groupby("country")["quantity"].sum().reset_index()
total_returned_items_per_country.rename(columns={"quantity": "total_returned_items"}, inplace=True)
total_returned_items_per_country

                    country  total_returned_items
0                     Gabon                    61
1                      Iraq                    27
2           Kyrgyz Republic                    24
3                  Maldives                    36
4  Turks and Caicos Islands                    22
5                    Zambia                    23

In [35]:
return_rate_result = total_items_per_country.merge(total_returned_items_per_country, on="country")
return_rate_result["return_rate"] = return_rate_result["total_returned_items"] / return_rate_result["total_sold_items"]
return_rate_result = return_rate_result[["country", "return_rate"]]
return_rate_result

                    country  return_rate
0                     Gabon     1.000000
1                      Iraq     1.000000
2           Kyrgyz Republic     1.000000
3                  Maldives     1.000000
4  Turks and Caicos Islands     0.536585
5                    Zambia     1.000000